[package]
name = "meet4k"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9"
hexdump = "*"
nix = "*"
errno = "*"
hex = "*"
glob = "*"
enum_dispatch = "*"
